### ISSUE TITLE
Client integration tests no longer run properly

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor.VSCode#168]
They always hang.

**Comment by SteveSandersonMS** [comment]
Well, the weird thing it did before (where it just hung forever, as if the underlying promises library was broken) is no longer happening since I updated to the latest VS Code. So unless you did something to fix this @NTaylorMullen, it looks like it was a defect in VS Code or another dependency that's since been fixed.

However now the tests are running again I found several places where the tests have become broken. These are all fixed in #211.
