### ISSUE TITLE
Is this extension available in public C# extension 1.16.2

### ISSUE THREAD

**Issue by John0King** [aspnet/Razor.VSCode#183]
I updated the vs-code and C# extensions today , and it does not work for me (no language server start when i open .cshtml file).
Is there any additional step before I use this extension ?

**Comment by NTaylorMullen** [comment]
Ah, @John0King the Razor support is not yet available in the 1.16.X C# extension build; it'll be available in 1.17. As of right you can get it in the form of a GitHub only pre-release. It can be downloaded [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.17.0-beta5).

We're in the process of getting out another build for a `beta6` of the 1.17 release because of [this](https://github.com/aspnet/Razor.VSCode/issues/174) issue. Once we have a good consensus that these beta GitHub-first releases are of a high enough quality it'll be included when you install the latest C# extension (shouldn't be long 😉)

**Comment by mikes-gh** [comment]
I would leave this open until 1.17 in case anyone has the same question

**Comment by NTaylorMullen** [comment]
> I would leave this open until 1.17 in case anyone has the same question

Good point, will do!

**Comment by mikes-gh** [comment]
Close now 1.17 is out?

**Comment by NTaylorMullen** [comment]
> Close now 1.17 is out?

Thanks @mikes-gh!
