### ISSUE TITLE
git clean -xdff sometimes results in Microsoft.AspNetCore.Razor.VSCode dir being deleted

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor.VSCode#201]
![image](https://user-images.githubusercontent.com/2008729/47111739-33c6b800-d209-11e8-85df-e86276324b98.png)

**Comment by SteveSandersonMS** [comment]
Yes, this is a known issue in Git on Windows: https://github.com/git-for-windows/git/issues/607. There's an outstanding PR with a fix: https://github.com/git-for-windows/git/pull/1414

Until the fix is merged and Git is updated, I'd recommend running `git reset --hard` after each time you run `git clean` to put the deleted files back.
