### ISSUE TITLE
1.0.0-alpha2-20181112.3 not on Linux

### ISSUE THREAD

**Issue by egbertn** [aspnet/Razor.VSCode#291]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce
Fresh install on WSL
Create a new webapi project
dotnet new webapi (or you could use mvc)

Open VS Code version 1.31.0

#### Description of the problem:
Extension will not load, Server will shut down

Note, *all files* are in the specified directory.

Expected behavior:

Loaded extension
--------------------------------------------------------------------------------
Razor.VSCode version 1.0.0-alpha2-20181112.3
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To log issues with the Razor experience in VSCode you can file issues at https://github.com/aspnet/Razor.VSCode
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
-----------------------------------------------------------------------------------------------------------------------------

[Info  - 15:17:20] Connection to server got closed. Server will restart.
Failed to load �z�, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/egbert/.vscode/extensions/ms-vscode.csharp-1.17.1/.razor/libcoreclr.so'
Failed to load �Z, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/egbert/.vscode/extensions/ms-vscode.csharp-1.17.1/.razor/libcoreclr.so'
[Info  - 15:17:21] Connection to server got closed. Server will restart.
Failed to load ���, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/egbert/.vscode/extensions/ms-vscode.csharp-1.17.1/.razor/libcoreclr.so'
[Info  - 15:17:21] Connection to server got closed. Server will restart.
Failed to load �:�, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/egbert/.vscode/extensions/ms-vscode.csharp-1.17.1/.razor/libcoreclr.so'
[Info  - 15:17:21] Connection to server got closed. Server will restart.
Failed to load �
[, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/egbert/.vscode/extensions/ms-vscode.csharp-1.17.1/.razor/libcoreclr.so'
[Error - 15:17:21] Connection to server got closed. Server will not be restarted.
Actual behavior:

#### Additional information

Please also provide the following to help debug the issue:

1. Razor (cshtml) file content
2. Generated C# code from the Razor CSharp Output in VS Code. To obtain this, right-click inside your .cshtml file and select "Command Palette". Search for and select "Razor: Show Razor CSharp".
3. Verbose Razor log output. For instructions on capturing this log, please see https://github.com/aspnet/Razor.VSCode/wiki/How-to-capture-verbose-log-output
4. OmniSharp log output. To find this, open VS Code's "Output" pane, then in the dropdown choose "OmniSharp Log".

**Comment by NTaylorMullen** [comment]
@egbertn thanks for the detailed bug report. We're tracking the fix of this issue here: https://github.com/aspnet/Razor.VSCode/issues/223

**Comment by Peter-JanGootzen** [comment]
I and a fellow student are both experiencing this issue. The Razor Log with this issue is different than in #223 and libunwind is installed, so this might be unrelated to #223.  This is on VSCode 1.31.1 and C# plugin version 1.17.1.
Razor Log with Verbose:

`Razor.VSCode version 1.0.0-alpha2-20181112.3
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Verbose'
 - To log issues with the Razor experience in VSCode you can file issues at https://github.com/aspnet/Razor.VSCode
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
-----------------------------------------------------------------------------------------------------------------------------

[Client - 8:48:55 PM] Starting Razor Language Server...
[Client - 8:48:55 PM] Server started, waiting for client to be ready...
[Info  - 8:48:56 PM] Connection to server got closed. Server will restart.
[Info  - 8:48:56 PM] Connection to server got closed. Server will restart.
[Info  - 8:48:57 PM] Connection to server got closed. Server will restart.
[Info  - 8:48:58 PM] Connection to server got closed. Server will restart.
[Error - 8:48:59 PM] Connection to server got closed. Server will not be restarted.

`

OmniSharp Log:

`Starting OmniSharp server at 2/21/2019, 8:48:55 PM
    Target: /home/peter-jan/Code/INF/tmp/ProjectAPI/ProjectWeb.sln

OmniSharp server started.
    Path: /home/peter-jan/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/run
    PID: 18424

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on arch 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/home/peter-jan/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/peter-jan/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/home/peter-jan/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin"
            MSBuildExtensionsPath = /home/peter-jan/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /home/peter-jan/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/peter-jan/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/peter-jan/Code/INF/tmp/ProjectAPI'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/peter-jan/Code/INF/tmp/ProjectAPI/ProjectWeb.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/peter-jan/Code/INF/tmp/ProjectAPI/ProjectWeb.API/ProjectWeb.API.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/peter-jan/Code/INF/tmp/ProjectAPI'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/peter-jan/Code/INF/tmp/ProjectAPI' on host 18306.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/peter-jan/Code/INF/tmp/ProjectAPI/ProjectWeb.API/ProjectWeb.API.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/peter-jan/Code/INF/tmp/ProjectAPI/ProjectWeb.API/ProjectWeb.API.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/peter-jan/Code/INF/tmp/ProjectAPI/ProjectWeb.API/ProjectWeb.API.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ProjectWeb.API
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /home/peter-jan/Code/INF/tmp/ProjectAPI/ProjectWeb.Database/ProjectWeb.Database.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/peter-jan/Code/INF/tmp/ProjectAPI/ProjectWeb.Database/ProjectWeb.Database.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/peter-jan/Code/INF/tmp/ProjectAPI/ProjectWeb.Database/ProjectWeb.Database.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/peter-jan/Code/INF/tmp/ProjectAPI/ProjectWeb.Database/ProjectWeb.Database.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/peter-jan/Code/INF/tmp/ProjectAPI/ProjectWeb.Database/ProjectWeb.Database.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ProjectWeb.Database`

**Comment by NTaylorMullen** [comment]
Interesting. @Peter-JanGootzen what flavor/bitness of Linux are you on?

**Comment by tgemelgo** [comment]
I'm having the same problem and tested with ubuntu 18.04 and 18.10

**Comment by Peter-JanGootzen** [comment]
> Interesting. @Peter-JanGootzen what flavor/bitness of Linux are you on?

I am on Arch Linux with everything upgraded.

**Comment by egbertn** [comment]
I am on Debian on WSL 64bit. It's really not 'Linux' distribution related. I'm afraid.

**Comment by NTaylorMullen** [comment]
@tgemelgo your issue is different than the ones listed in this issue.  See https://github.com/aspnet/Razor.VSCode/issues/298#issuecomment-467097413 for more context.

@egbertn and @Peter-JanGootzen thanks for the update. Ya I'll have to rebuild the VSCode extension with a newer Core CLR. Stay tuned, i'll do my best to ensure this is fixed in the next release.
